name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authorize SSH Connections
      uses: mnavarrocarter/authorize-aws-security-group-ingress-action@v1.0.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1' # Your AWS region
        aws-security-group-id: ${{ secrets.AWS_SSH_SECURITY_GROUP_ID }}
        protocol: 'tcp'
        port: 22

    - name: Pull changes on Production Server
      uses: appleboy/ssh-action@master
      with:
        host: ec2-54-82-90-29.compute-1.amazonaws.com
        username: appsmith
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/appsmith/appsmith/stacks/git-storage/654aaabe7cc2433ce3db51f9
          ${{ secrets.SCRIPT }}
