name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull changes on Production Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ ec2-54-82-90-29.compute-1.amazonaws.com }}
        username: ${{ appsmith }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/appsmith/appsmith/stacks/git-storage/654aaabe7cc2433ce3db51f9
          git pull origin master
